### ISSUE TITLE
Duplication of CSS rules in the result bundle (ver 7.0.0)

### ISSUE THREAD

**Issue by mxmknnv** [postcss/postcss-custom-properties#103]
I updated plugin to ver. 7.0.0 and I have noticed that CSS rules are duplicated. I rolled back plugin to ver. 6.3.1 and it looks fine. I can assume that this is common issue with [this](https://github.com/postcss/postcss-custom-properties/issues/98) and [this](https://github.com/postcss/postcss-custom-properties/issues/102). 

Before update 7.0.0:
<img width="537" alt="1 before" src="https://user-images.githubusercontent.com/4584273/37151106-0df54ed8-22f6-11e8-8f01-3901242bd794.png">
After update 7.0.0:
<img width="693" alt="1 after" src="https://user-images.githubusercontent.com/4584273/37151104-0da96338-22f6-11e8-85af-4c0d9687279d.png">
After update 7.0.0 and I switched off "postcss-calc" plugin:
<img width="672" alt="1 after-calc-off" src="https://user-images.githubusercontent.com/4584273/37151105-0dcf32fc-22f6-11e8-8cc5-090b34c024cd.png">

Before:
<img width="1440" alt="1 1before" src="https://user-images.githubusercontent.com/4584273/37151274-9d29507c-22f6-11e8-8926-10c95302acb5.png">
After:
<img width="1440" alt="1 1after" src="https://user-images.githubusercontent.com/4584273/37151304-c2ca90de-22f6-11e8-93cb-cc06b24b24e8.png">

Before:
<img width="1440" alt="2 before" src="https://user-images.githubusercontent.com/4584273/37151318-d04765d4-22f6-11e8-9840-b0bce9c80051.png">
After:
<img width="1440" alt="2 after" src="https://user-images.githubusercontent.com/4584273/37151327-d80b56e0-22f6-11e8-9ad4-ccfc8c97a93a.png">

My postcss.config.js file:
> module.exports = ({ file, options, env }) => ({
>   plugins: {
>     'postcss-import': {},
>     'postcss-nested': {},
>     'postcss-custom-properties': {},
>     'postcss-calc': {},
>     'autoprefixer': env == 'production' ? { browsers: ['last 2 versions'] } : false,
>     'cssnano': env === 'production' ? {} : false,
>   },
> });

**Comment by jonathantneal** [comment]
This Custom Properties plugin works like Autoprefixer, adding the compiled declarations as a _fallback_, in the same way Autoprefixer adds vendor-prefixed declarations as a fallback. What you’ve reported is a feature, and a breaking change from v6. If you want to compile variables regardless of browser support, use the [`preserve`](https://github.com/postcss/postcss-custom-properties#preserve) option.

```js
postCSSCustomProperties({
  preserve: false
})
```

The issues you’ve linked to are very different. The first issue was with someone saying that parsing wasn’t working correctly, which should have now been closed due to inactivity. The second is someone saying we should include an option to export variables to their own file, which I’m still lookin into in my spare time.

**Comment by mxmknnv** [comment]
@jonathantneal thank you for quick response!

**Comment by jonathantneal** [comment]
@mxmknnv, hey thanks for writing that. I was fretting for a good 10 minutes that my response was too terse. I don’t want to discourage anyone.
