### ISSUE TITLE
Bring back warning option

### ISSUE THREAD

**Issue by danny-andrews-snap** [postcss/postcss-custom-properties#159]
I'm gonna go out on a limb here and say that the `warning` option should be brought back. I understand that you think it is the job of a linter, but I kindly disagree. :) Follow with me, and please correct me if I'm wrong on any of these points:

1. Anyone using this plugin is developing for at least one browser which does not support custom properties.
2. If any undefined properties are encountered, that bit of CSS won't work on said browser(s).
3. This is a bug which the user should be informed about _as early as possible_.

Why leave this type of thing up to a linter? Just this week I ran into an issue where custom properties were not being replaced, and didn't realize it until trying my code in IE. The `warning` option [already defaulted to `false`](https://github.com/postcss/postcss-custom-properties/releases/tag/7.0.0), so it didn't bother anyone who didn't specifically opt-in to it, so why remove it for those who want to use it?

From the release notes:
> Changed: warnings option defaults to false to reflect the browser climate

I appreciate the forward-thinkingness, but if you think the browser climate is so good, shouldn't you just deprecate this plugin as it's not needed anymore? 🤷‍♂️

The majority of developers have to write code for browsers without custom properties support. Why not give them hints about conditions which could break their code?

Thanks!

Related #153, #117.

**Comment by danny-andrews-snap** [comment]
> However, a fair number of PostCSS Preset Env users are not providing Custom Property fallbacks for IE, because their browserslist does not include IE.

In that case, wouldn't PostCSS Preset Env just exclude this plugin altogether? Why perform redundant work, and duplicate custom property values if you are developing for a browser which supports them without transformation?

**Comment by jonathantneal** [comment]
I’m always willing to listen to new ideas and arguments, as well as rehash old ones, but I consider it bad form to open new issues and also critique what I’m saying on dead issues.

I do see that you commented there and then here. Thank you for correcting me. I need to figure out how to lock dead issues, as I errantly became very worried you would create multiple threads for me to respond to.

**Comment by jonathantneal** [comment]
I’m re-opening the issue so others can contribute. I still feel the same way, but I don’t want my misunderstanding to get in the way of proper discussions and development.

**Comment by danny-andrews-snap** [comment]
I understand the concern. OSS development is a thankless job, and developers can be entitled brats. :)

**Comment by hirokiosame** [comment]
I think the warnings should be brought back as well.

Since this plugin statically compiles the variables, if the plugin can't find it, it should emit a warning. 

I think the linting rule is appropriate for catching missing variables when using the native custom-properties feature (dynamic CSS variables), but isn't appropriate to catch compilation errors.

**Comment by danny-andrews-snap** [comment]
But again, why would you be using this plugin if you are developing for a browser which supports custom properties natively?

I think in cases like this, it helps to think of the average use-case. I can't say for sure, but I would reckon that the majority of users of this plugin are developing for at least one browser which doesn't support native custom properties. As such, if they have a custom property lacking a definition, they will get unexpected behavior when they deploy their code (e.g. why isn't this font `--my-custom-color`?). Giving them the ability to be warned for properties with no matching definition helps them to catch this error case early.

**Comment by stefanmaric** [comment]
@jonathantneal I was looking around for info on how to report (warn or bail) the use of undefined properties (with or without fallback) and also the declaration of unused ones.

Do you know the existence of such rules/plugins for stylelint?

If not, is it even possible? —  How would a stylelint plugin match property declarations to `var()` invocations across `@imports` (assuming you're using the postcss-import plugin for your css compilation) and the files imported with `importFrom`? I would guess the stylint plugin would have to replicate all the logic of `postcss-custom-properties` and the user would have to take great care to keep the configs in sync.

I feel these features are worth to be included here because they are very implementation-specific.

**Comment by jonathantneal** [comment]
All of this is possible with:

https://www.npmjs.com/package/stylelint-value-no-unknown-custom-properties

And it uses the same style of options as this plugin.

**Comment by stefanmaric** [comment]
> https://www.npmjs.com/package/stylelint-value-no-unknown-custom-properties

Alright, it is implemented as I expected. Not ideal, but works nonetheless. :smile: 

I will try to create one for the unused ones. Or does it exist already?
