### ISSUE TITLE
warnings used without a fallback 

### ISSUE THREAD

**Issue by Memoyr** [postcss/postcss-custom-properties#56]
is it possible to deactivate this warning, "used without a fallback " ? 
thanks

**Comment by Skotu** [comment]
Yes, it's annoying me a lot, so would like to have some option to deactivate it.

**Comment by peterschmiz** [comment]
As far as I could understand - based on the source code - neither strict or warnings options key has any effect on the warning :(

**Comment by archansel** [comment]
+1

**Comment by bradennapier** [comment]
+1000

I have about 180 copies of 40 variables because I need to include :root() in EVERY single css file due to this problem.

I have a root level of variables and 1000's of css files in our app that all expect to reference the variables (theme) in the globally included css file.  

This completely kills the app since I either geet thousands of lines of warnings on every save or I get thousands of lines of redundant css 

![image](https://user-images.githubusercontent.com/15365418/27205057-64007abc-51e3-11e7-9b61-2bbcfe36c351.png)

**Comment by s-panferov** [comment]
Please add an ability to disable the warning. In out product we use both "real" and "fake" css-properties, and this warning is annoying.

**Comment by LeaVerou** [comment]
Add me to the list of people wanting to suppress this warning. I've used `warnings: false`, doesn't do anything.

**Comment by LeaVerou** [comment]
If anyone wants to work on a PR, the relevant line seems to be: https://github.com/postcss/postcss-custom-properties/blob/4031a441c26a538dfb35468795e7e2703290b510/index.js#L45

However, `warnings` is not defined in that scope, so it doesn't seem as trivial as just wrapping that with an `if (warnings) { ... }` :/

**Comment by jonathantneal** [comment]
Would #67 also work as a solution, @LeaVerou? I’ve requested permission to resolve and merge it ASAP.

**Comment by LeaVerou** [comment]
@jonathantneal the code is a bit awkward, but it should work.

**Comment by jonathantneal** [comment]
Resolved via #67, published as 6.1.0.

**Comment by SuperOl3g** [comment]
And how about to add the ability to turn this warning into error.
